version: '2'

services: 
  express:
    build: .
    image: shintech/docker_express:latest
    container_name: shintech-express
    env_file:
      - ./docker.env
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./data:/data